CREATE TABLE IF NOT EXISTS `Sessions` (
  `session_id` VARCHAR(128) NOT NULL PRIMARY KEY,
  `data` JSON NOT NULL,
  `expires_at` TIMESTAMP(3) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_sessions_expires_at` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
